---
- name: ensure php msgpack extension is installed
  shell: yes '' | pecl install msgpack-{{ pecl_msgpack_version }}
  register: pecl_msgpack_result
  changed_when: "'installed' not in pecl_msgpack_result.stdout"
  failed_when: "'ERROR' in pecl_msgpack_result.stdout"

- name: ensure php zmq extension is installed
  shell: yes '' | pecl install zmq-{{ pecl_zmq_version }}
  register: pecl_zmq_result
  changed_when: "'installed' not in pecl_zmq_result.stdout"
  failed_when: "'ERROR' in pecl_zmq_result.stdout"

- name: ensure php zmq extension is installed
  shell: yes '' | pecl install zmq-{{ pecl_zmq_version }}
  register: pecl_zmq_result
  changed_when: "'installed' not in pecl_zmq_result.stdout"
  failed_when: "'ERROR' in pecl_zmq_result.stdout"
  when: pecl_zmq_version != '1.1.3'

- name: git clone zmq repo
  git:
    repo: "{{ zmq_source_repo }}"
    dest: "/tmp/php-zmq"
    version: "master"
  when: pecl_zmq_version == '1.1.3'

- name: install php-zmq 1.1.3
  shell: phpize && ./configure && make && make install
  args:
    chdir: /tmp/php-zmq
  when: pecl_zmq_version == '1.1.3'

- name: ensure zmq and msgpack extension present in php.d/*.ini
  template:
    src: package.ini.j2
    dest: "/etc/php.d/{{ item }}.ini"
  with_items:
    - zmq
    - msgpack
  notify: restart php-fpm
